name: Post PRs to Teams

on:
  pull_request:
    types:
      - ready_for_review

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Notify
        uses: davidwengier/PostAdaptiveCard@v1.0.4
        with:
          webhook_uri: ${{ secrets.TEAMS_PR_WEBHOOK }}